package com.example.myapplication.di.restaurant;

import com.example.myapplication.data.repository.restaurant.RestaurantMenuRepository;
import com.example.myapplication.domain.usecase.restaurant.menu.AddDishUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.AddMenuCategoryUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.DeleteCategoryUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.DeleteDishUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.GetCategoriesUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.GetDishesMenuOwnerModelsUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.GetSingleDishByIdUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.UpdateDishDataUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.images.GetCategoriesImagesUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.images.GetDishesImagesUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.images.GetSingleDishImageUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.images.UploadCategoryUriImageUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.images.UploadDishImageUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.requireChoices.AddNewRequireChoiceVariantUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.requireChoices.AddRequiredChoicesUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.requireChoices.DeleteRequiredChoiceByIdUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.requireChoices.DeleteRequiredChoiceVariantUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.requireChoices.GetRequiredChoicesUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.requireChoices.GetSingleRequiredChoiceByIdUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.requireChoices.UpdateRequiredChoiceNameUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.requireChoices.UpdateRequiredChoiceVariantUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.toRemove.AddIngredientsToRemoveUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.toRemove.DeleteIngredientToRemoveUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.toRemove.GetIngredientsToRemoveUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.toRemove.UpdateIngredientsToRemoveUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.toppings.AddToppingUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.toppings.DeleteToppingImageUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.toppings.DeleteToppingUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.toppings.GetToppingsImagesUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.toppings.GetToppingsUseCase;
import com.example.myapplication.domain.usecase.restaurant.menu.toppings.UploadToppingImage;

public class RestaurantMenuDI {
    public static RestaurantMenuRepository restaurantMenuRepository = new RestaurantMenuRepository();
    public static RestaurantMenuRepository.MenuImages menuImages = new RestaurantMenuRepository.MenuImages();
    public static RestaurantMenuRepository.Toppings toppings = new RestaurantMenuRepository.Toppings();
    public static RestaurantMenuRepository.RequiredChoice requiredChoice = new RestaurantMenuRepository.RequiredChoice();
    public static RestaurantMenuRepository.IngredientsToRemove toRemove = new RestaurantMenuRepository.IngredientsToRemove();

    public static DeleteCategoryUseCase deleteCategoryUseCase = new DeleteCategoryUseCase();
    public static DeleteDishUseCase deleteDishUseCase = new DeleteDishUseCase();
    public static GetCategoriesImagesUseCase getCategoriesImagesUseCase = new GetCategoriesImagesUseCase();
    public static GetDishesImagesUseCase getDishesImagesUseCase = new GetDishesImagesUseCase();
    public static GetCategoriesUseCase getCategoriesUseCase = new GetCategoriesUseCase();
    public static GetDishesMenuOwnerModelsUseCase getDishesMenuOwnerModelsUseCase = new GetDishesMenuOwnerModelsUseCase();
    public static GetSingleDishByIdUseCase getSingleDishByIdUseCase = new GetSingleDishByIdUseCase();
    public static UpdateDishDataUseCase updateDishDataUseCase = new UpdateDishDataUseCase();
    public static DeleteIngredientToRemoveUseCase deleteIngredientToRemoveUseCase = new DeleteIngredientToRemoveUseCase();
    public static UpdateIngredientsToRemoveUseCase updateIngredientsToRemoveUseCase = new UpdateIngredientsToRemoveUseCase();
    public static UpdateRequiredChoiceNameUseCase updateRequiredChoiceNameUseCase = new UpdateRequiredChoiceNameUseCase();
    public static AddNewRequireChoiceVariantUseCase addNewRequireChoiceVariantUseCase = new AddNewRequireChoiceVariantUseCase();
    public static UpdateRequiredChoiceVariantUseCase updateRequiredChoiceVariantUseCase = new UpdateRequiredChoiceVariantUseCase();
    public static DeleteRequiredChoiceVariantUseCase deleteRequiredChoiceVariantUseCase = new DeleteRequiredChoiceVariantUseCase();
    public static DeleteRequiredChoiceByIdUseCase deleteRequiredChoiceByIdUseCase = new DeleteRequiredChoiceByIdUseCase();
    public static GetSingleRequiredChoiceByIdUseCase getSingleRequiredChoiceByIdUseCase = new GetSingleRequiredChoiceByIdUseCase();
    public static DeleteToppingUseCase deleteToppingUseCase = new DeleteToppingUseCase();
    public static DeleteToppingImageUseCase deleteToppingImageUseCase = new DeleteToppingImageUseCase();
    public static GetSingleDishImageUseCase getSingleDishImageUseCase = new GetSingleDishImageUseCase();
    public static AddDishUseCase addDishUseCase = new AddDishUseCase();
    public static AddMenuCategoryUseCase addMenuCategoryUseCase = new AddMenuCategoryUseCase();
    public static GetToppingsImagesUseCase getToppingsImagesUseCase = new GetToppingsImagesUseCase();
    public static UploadDishImageUseCase uploadDishImageUseCase = new UploadDishImageUseCase();
    public static UploadToppingImage uploadToppingImage = new UploadToppingImage();
    public static UploadCategoryUriImageUseCase uploadCategoryUriImageUseCase = new UploadCategoryUriImageUseCase();
    public static GetToppingsUseCase getToppingsUseCase = new GetToppingsUseCase();
    public static GetIngredientsToRemoveUseCase getIngredientsToRemoveUseCase = new GetIngredientsToRemoveUseCase();
    public static GetRequiredChoicesUseCase getRequiredChoicesUseCase = new GetRequiredChoicesUseCase();
    public static AddToppingUseCase addToppingUseCase = new AddToppingUseCase();
    public static AddIngredientsToRemoveUseCase addIngredientToRemoveUseCase = new AddIngredientsToRemoveUseCase();
    public static AddRequiredChoicesUseCase addRequiredChoicesUseCase = new AddRequiredChoicesUseCase();
}
